Djamazon/Djamazon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Djamazon/app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='app/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('product/<int:product_id>/', views.detail, name='detail'),
    path('fav_products/', views.fav_products, name='fav_products'),
    path('toggle_fav_product_status/', views.toggle_fav_product_status, name='toggle_fav_product_status'),
    path('cart/', views.cart, name='cart'),
    path('change_item_amount/', views.change_item_amount, name='change_item_amount'),
    path('order_history/', views.order_history, name='order_history'),
]

Djamazon/memo/app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:memo_id>', views.detail, name='detail'),
    path('new_memo', views.new_memo, name='new_memo'),
    path('delete_memo/<int:memo_id>', views.delete_memo, name='delete_memo'),
    path('edit_memo/<int:memo_id>', views.edit_memo, name='edit_memo')
]

Djamazon/memo/memo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

Djamazon/memo/app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <title>めっちゃ使いやすいメモ</title>
  <link rel="stylesheet" type="text/css" href="{% static 'app/css/style.css' %}">
</head>

<body>

  <h1>めっちゃ使いやすいメモ</h1>

  <div class="container">
    {% block content %}{% endblock %}
  </div>
</body>
</html>

Djamazon/memo/app/templates/app/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% extends 'app/base.html' %}
    {% block content %}


    <div>
        <a href="{% url 'app:index' %}">ホームに戻る</a>
      </div>
      
      <h2>{{ memo.title }}</h2>
      <div>
        {{ memo.text | linebreaks | urlize }}
      </div>

      <button><a class='btn' href="{% url 'app:edit_memo' memo.pk %}">編集</a></button>

      <form method="post" action="{% url 'app:delete_memo' memo.pk %}">{% csrf_token %}
        <button class="btn" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
      </form>

      {% endblock %}
</body>
</html>

Djamazon/memo/app/templates/app/edit_memo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% extends 'app/base.html' %}
    {% block content %}

      <div>
        <a href="{% url 'app:detail' memo.id %}">戻る</a>
      </div>
      
      <form action="{% url 'app:edit_memo' memo.id %}" method="POST">{% csrf_token %}
        <table>
          <tr>
            <th>タイトル</th>
            <td>{{ form.title }}</td>
          </tr>
          <tr>
            <th>テキスト</th>
            <td>{{ form.text }}</td>
          </tr>
        </table>
        <button class="btn" type="submit">保存</button>
      </form>

      {% endblock %}
</body>
</html>

Djamazon/memo/app/templates/app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% extends 'app/base.html' %}
    {% block content %}


    <a class="btn" href="{% url 'app:new_memo' %}">新規メモ作成</a>

    {% for memo in memos %}
    <a href="{% url 'app:detail' memo.id %}" class="memo-title">
      <div>
        {{ memo }}
        <span class="updated_datetime">{{ memo.updated_datetime }}</span>
      </div>
    </a>
    {% endfor %}

    {% endblock %}
</body>
</html>

Djamazon/memo/app/templates/app/new_memo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
        {% extends 'app/base.html' %}
        {% block content %}


    <div>
        <a href="{% url 'app:index' %}">ホームに戻る</a>
    </div>

    <form action="{% url 'app:new_memo' %}" method="POST">{% csrf_token %}
        {{form.as_p}}
        <button type='submit' class='btn'>保存</button>
    </form>

    {% endblock %}
</body>
</html>