SNS/SNS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bordapp.urls')),
]

SNS/bordapp/urls.py
from django.urls import path
from . import views
from .views import BoardCreate
from django.conf import settings
from django.conf.urls.static import static


app_name = 'bordapp'
urlpatterns = [
    path('signup/', views.signupfunc, name='signup'),
    path('login/', views.loginfunc, name='login'),
    path('list/', views.listfunc, name='list'),
    path('logout/', views.logoutfunc, name='logout'),
    path('detail/<int:pk>', views.detailfunc, name='detail'),
    path('good/<int:pk>', views.goodfunc, name='good'),
    path('read/<int:pk>', views.readfunc, name='read'),
    path('create/', BoardCreate.as_view(), name='create'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

SNS/bordapp/models.py
from django.db import models

class BoardModel(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    auther = models.CharField(max_length=100)
    images = models.ImageField(upload_to='')
    good = models.IntegerField(null=True, blank=True, default=0)
    read = models.IntegerField(null=True, blank=True, default=0)
    readtext = models.CharField(max_length=200, null=True, blank=True, default='a')

SNS/bordapp/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect
from .models import BoardModel
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.generic import CreateView
from django.urls import reverse_lazy


def signupfunc(request):
    if request.method == 'POST':
        username2 = request.POST['username']
        password2 = request.POST['password']

        # tryを実行して合致したらtryを最後まで実行する。そうでなければexceptを実行する。
        # この場合、tryはusername2が既に登録されているか確認する。
        # そうでなければexceptを実行する。
        try:
            User.objects.get(username=username2)
            return render(request, 'bordapp/signup.html', {'error': 'このユーザーは登録されています'})
        except:
            user = User.objects.create_user(username2, '', password2)
            return render(request, 'bordapp/signup.html')

    return render(request, 'bordapp/signup.html')


def loginfunc(request):
    if request.method == 'POST':
        username2 = request.POST['username']
        password2 = request.POST['password']
        user = authenticate(request, username=username2, password=password2)
        # もしユーザーがいなくなかったら(=存在する場合)
        if user is not None:
            login(request, user)
            return redirect('bordapp:list')
        else:
            return redirect('bordapp:login')
    return render(request, 'bordapp/login.html')

@login_required
def listfunc(request):
    object_list = BoardModel.objects.all()
    return render(request, 'bordapp/list.html', {'object_list': object_list})


def logoutfunc(request):
    logout(request)
    return redirect('bordapp:login')

    
def detailfunc(request, pk):
    object = BoardModel.objects.get(pk=pk)
    return render(request, 'bordapp/detail.html', {'object': object})


def goodfunc(request, pk):
    post = BoardModel.objects.get(pk=pk)
    post.good = post.good + 1
    post.save()
    return redirect('bordapp:list')


def readfunc(request, pk):
    post = BoardModel.objects.get(pk=pk)
    post2 = request.user.get_username()
    if post2 in post.readtext:
        return redirect('bordapp:list')
    else:
        post.read += 1
        post.readtext = post.readtext + '' + post2
        post.save()
        return redirect('bordapp:list')


class BoardCreate(CreateView):
    template_name = 'bordapp/create.html'
    model = BoardModel
    fields = ('title', 'content', 'auther', 'images')
    success_url = reverse_lazy('bordapp:list')

SNS/templates/bordapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0-11/css/all.min.css">
<!-- <link rel="stylesheet" href="style.css"> -->



{% block customcss %}
{% endblock customcss %}



<title>Title</title>
</head>
<body>

{% block header %}
{% endblock header%}







{% block content %}
{% endblock content%}










<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

SNS/templates/bordapp/create.html
{% extends 'bordapp/base.html' %}


{% block header %}
<div class="alert alert-primary" role="alert">新規作成</div>
{% endblock header %}


{% block content %}

{% if user.is_authenticated %}
<form action='' method='POST' enctype="multipart/form-data">{% csrf_token %}
<p>タイトル：<input type='text' name='title'></p>
<p>内容：<input type='text' name='content'></p>
<p>画像：<input type='file' name='images'></p>
<input type='hidden' name='auther' value='{{ user.username }}'>

<input type='submit' value='作成する'>
</form>
{% else %}
ログインしてください
{% endif %}

{% endblock content %}

SNS/templates/bordapp/detail.html
{% extends 'bordapp/base.html' %}



{% block customcss %}

{% endblock customcss %}



{% block header %}
<div class="alert alert-primary" role="alert">
    個別投稿
  </div>

{% endblock header %}



{% block content %}
<div class="container">
  
<div class="alert alert-success" role="alert">
    <p>タイトル : {{ object.title }}</p>
    <p>投稿者 : {{ object.auther }}</p>
    <p>内容 : {{ object.content }}</p>
    <p><img src="{{ object.images.url }}" width="300"></p>
    <a href="{% url 'bordapp:good' object.pk %}" class="btn btn-primary" role="button" aria-pressed="true">イイね！</a>
<a href="{% url 'bordapp:read' object.pk %}" class="btn btn-secondary " role="button" aria-pressed="true">既読</a>

  </div>
</div>
{% endblock content %}

SNS/templates/bordapp/list.html
{% extends 'bordapp/base.html' %}



{% block customcss %}

{% endblock customcss %}



{% block header %}
<div class="alert alert-primary" role="alert">
    社内SNS
  </div>

{% endblock header %}



{% block content %}
<div class="container">
{% for item in object_list %}
  
<div class="alert alert-success" role="alert">
    <p>タイトル : <a href="{% url 'bordapp:detail' item.pk %}">{{ item.title }}</a></p>
    <p>投稿者 : {{ item.auther }}</p>
    <a href="#" class="btn btn-primary" role="button" aria-pressed="true">イイね : {{ item.good }}</a>
<a href="#" class="btn btn-secondary " role="button" aria-pressed="true">既読 : {{ item.read }}人</a>

  </div>
  {% endfor %}
  <a href="{% url 'bordapp:logout' %}">ログアウト</a>
</div>
{% endblock content %}

SNS/templates/bordapp/login.html
{% extends 'bordapp/base.html' %}


{% load static %}
{% block customcss %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock customcss %}


{% block content %}

<form class="form-signin" method="POST" action="">{% csrf_token %}
    <div class="text-center mb-4">
      <img class="mb-4" src="/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Log In</h1>
    </div>
  
    <div class="form-label-group">
      <input type="text" id="inputEmail" class="form-control" name='username' placeholder="Username" required autofocus>
      <label for="inputEmail">User Name</label>
    </div>
  
    <div class="form-label-group">
      <input type="password" id="inputPassword" class="form-control" name='password' placeholder="Password" required>
      <label for="inputPassword">Password</label>
    </div>
  
    <div class="checkbox mb-3">
      
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Log In</button>
    <p class="mt-5 mb-3 text-muted text-center">&copy; Daiki Yamada</p>
  </form>

  {% endblock content %}

SNS/templates/bordapp/signup.html
{% extends 'bordapp/base.html' %}

{% load static %}
{% block customcss %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock customcss %}


{% block content %}

<form class="form-signin" method="POST" action="">{% csrf_token %}
    <div class="text-center mb-4">
      <img class="mb-4" src="/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Sign Up</h1>
    </div>

    {% if error %}
    {{ error }}
    {% endif %}
  
    <div class="form-label-group">
      <input type="text" id="inputEmail" class="form-control" name='username' placeholder="Username" required autofocus>
      <label for="inputEmail">User Name</label>
    </div>
  
    <div class="form-label-group">
      <input type="password" id="inputPassword" class="form-control" name='password' placeholder="Password" required>
      <label for="inputPassword">Password</label>
    </div>
  
    <div class="checkbox mb-3">
      
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
    <p class="mt-5 mb-3 text-muted text-center">&copy; Daiki Yamada</p>
  </form>

  {% endblock content %}