django_blog/blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:blog_id>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('delete/<int:blog_id>/', views.delete, name='delete'),
    path('edit/<int:blog_id>/', views.edit, name='edit')
]

django_blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]

django_blog/blogs/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title = models.CharField(blank=False, null=False, max_length=150)
    text = models.TextField(blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

django_blog/blogs/forms.py
from django.forms import ModelForm
from .models import Blog

class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['title','text']

django_blog/blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Blog
from .forms import BlogForm
from django.views.decorators.http import require_POST

# Create your views here.

def index(request):
    blogs = Blog.objects.order_by('-created_datetime')
    return render(request, 'blogs/index.html', {'blogs': blogs})

def detail(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    return render(request, 'blogs/detail.html', {'blog': blog})

def new(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:index')
    else:
        form = BlogForm
        return render(request, 'blogs/new.html', {'form': form})

@require_POST
def delete(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    blog.delete()
    return redirect('blogs:index')

def edit(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    if request.method == "POST":
        form = BlogForm(request.POST, instance=blog)
        if form.is_valid():
            form.save()
            return redirect('blogs:detail', blog_id=blog_id)
    else:
        form = BlogForm(instance=blog)
    return render(request, 'blogs/edit.html', {'form': form, 'blog':blog})

django_blog/blogs/templates/blogs/detail.html
<!DOCTYPE html>
<html>
<head>
  <title>ブログアプリ</title>
</head>
<body>
  
<h1 style="text-align: center;">{{ blog.title }}</h1>
    <div style="width: 70%;margin: 0px auto;">
        <div>
            <div style="margin: 60px 20px;">
                {{ blog.text }}
            </div>

            <div style="text-align: center; margin-top: 50px">
            <a href="{% url 'blogs:edit' blog.id %}">
            <button class="btn">編集</button></a>

            <form method="post" action="{% url 'blogs:delete' blog.id %}">{%csrf_token %}
                <button class="btn" type="submit" onclick='return confirm("本当に削除しますか?");'>削除</button> 
            </form>
        </div>

        <div style="text-align: center; margin-top: 50px">
            <a href="{% url 'blogs:index' %}">トップページに戻る</a>
        </div>
      </div>
  </div>
</body>
</html>

django_blog/blogs/templates/blogs/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ブログ編集</title>
</head>
<body>
    <h1 style="text-align: center;">記事編集</h1>
        <div style="width: 70%;margin: 0px auto;">
            <div>
                <div style="margin: 60px 20px;">
                    <form action="{% url 'blogs:edit' blog.id %}" method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                    <button class="btn" type="submit">保存</button> </form>
                </div>
                <div style="text-align: center; margin-top: 50px">
                    <a href="{% url 'blogs:detail' blog.id %}">記事に戻る</a>
                </div>
            </div>
        </div>
</body>
</html>

django_blog/blogs/templates/blogs/index.html
<!DOCTYPE html>
<html>
<head>
  <title>ブログ管理サイト</title>
</head>
<body>
    <h1 style="text-align: center;">My Blog</h1> <div style="width: 70%;margin: 0px auto;">
    <a href="{% url 'blogs:new' %}">
    <button class="btn">新規記事作成</button>
        </a>
        <hr />
        {% for blog in blogs %}
        <div>
    <h3>{{ blog.title }}</h3>
    <div>{{ blog.text | truncatechars:100 }}</div> <div style="text-align: right;">
    <a href="{% url 'blogs:detail' blog_id=blog.id %}">記事を読む</a> </div>
        </div>
        <hr />
        {% endfor %}
      </div>
    </body>
</html>

django_blog/blogs/templates/blogs/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ブログ作成</title>
</head>
<body>
    <h1 style='text-align: center;'>新規記事作成</h1>
    <div style="width: 70%; margin: 0px auto;">
        <div>
            <div style='margin: 60px 20px'>
                <form action="{% url 'blogs:new' %}" method="POST">{% csrf_token %}
                    {{ form.as_p }}
                    <button type='submit' class='btn'>保存</button>
                </form>
            </div>
            <div style="text-align: center; margin-top: 50px;">
                <a href="{% url 'blogs:index' %}">トップページに戻る</a>
            </div>
        </div>
    </div>
</body>
</html>